<?php

namespace AppBundle\Repository;

/**
 * MedaillesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedaillesRepository extends \Doctrine\ORM\EntityRepository
{
}
