<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0uifwsx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0uifwsx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0uifwsx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0uifwsx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0uifwsx\appDevDebugProjectContainer(array(
    'container.build_hash' => '0uifwsx',
    'container.build_id' => '83d597c4',
    'container.build_time' => 1526558771,
), __DIR__.\DIRECTORY_SEPARATOR.'Container0uifwsx');
