<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRqzcpmx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRqzcpmx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRqzcpmx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRqzcpmx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRqzcpmx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rqzcpmx',
    'container.build_id' => '9d5e3729',
    'container.build_time' => 1526557220,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRqzcpmx');
